# Site settings
title: Muriel Gonzalez | Web Development
name: muriel gonzalez
email: murielgonzalez@gmail.com
email_encoded: "&#109;&#117;&#114;&#105;&#101;&#108;&#103;&#111;&#110;&#122;&#097;&#108;&#101;&#122;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
bio: >
  Web developer with a passion for learning and making things with web technologies. 
shortbio: >
  maker of things
baseurl: "" 
url: "" # the base hostname & protocol for your site
github_username:  murielg
repository: murielg/murielg.github.io
# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
exclude: ["node_modules","package.json", "Rakefile","Gemfile", "Gemfile.lock"]
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
